# Generated by Django 5.2.5 on 2025-09-05 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestate',
            name='is_inside',
            field=models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], max_length=10),
        ),
        migrations.AlterField(
            model_name='devicestate',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
